<?php

use App\Http\Controllers\BitsoController;
use App\Http\Controllers\BridgeController;
use App\Http\Controllers\Business\VirtualAccountsController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\CronController;
use App\Http\Controllers\CryptoWalletsController;
use App\Http\Controllers\DepositController;
use App\Http\Controllers\KycServiceController;
use App\Http\Controllers\LocalPaymentWebhookController;
use App\Http\Controllers\PaxosController;
use App\Models\BeneficiaryFoems as BeneficiaryForms;
use App\Models\PayinMethods;
use App\Models\payoutMethods;
use App\Services\OnrampService;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Route;
use Modules\Advcash\app\Http\Controllers\AdvcashController;
use Modules\Bitso\app\Http\Controllers\BitsoController as ControllersBitsoController;
use Modules\Flow\app\Http\Controllers\FlowController;
use Modules\VitaWallet\app\Http\Controllers\VitaWalletController;
use Modules\VitaWallet\app\Http\Controllers\VitaWalletTestController;
use App\Http\Controllers\CoinbaseOnrampController;
use App\Http\Controllers\TransFiController;
use App\Models\Business;
use App\Models\User;
use Bavix\Wallet\Models\Wallet;
use App\Models\Deposit;
use Modules\Customer\app\Http\Controllers\DojahVerificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get("payin-mm", function(){
    
    $payins = [
        0 => [
          'id' => 1,
          'method_name' => 'PSE',
          'gateway' => 'bitso',
          'country' => 'COL',
          'currency' => 'COP',
          'payment_mode' => 'bankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 50,
          'maximum_deposit' => 3500,
          'minimum_charge' => 0.44,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'COP,USD,MXN',
          'Exchange_rate_float' => 2,
        ],
        1 => [
          'id' => 2,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'ARG',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        2 => [
          'id' => 3,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'BOL',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        3 => [
          'id' => 4,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'BRA',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        4 => [
          'id' => 5,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'CHL',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        5 => [
          'id' => 6,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'COL',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        6 => [
          'id' => 7,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'CRI',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        7 => [
          'id' => 8,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'DOM',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        8 => [
          'id' => 9,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'ECU',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        9 => [
          'id' => 10,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'SLV',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        10 => [
          'id' => 11,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'GTM',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        11 => [
          'id' => 12,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'HND',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        12 => [
          'id' => 13,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'MEX',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        13 => [
          'id' => 14,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'NIC',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        14 => [
          'id' => 15,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'PAN',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        15 => [
          'id' => 16,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'PRY',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        16 => [
          'id' => 17,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'PER',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        17 => [
          'id' => 18,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'URY',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        18 => [
          'id' => 19,
          'method_name' => 'Volet(Advcash)',
          'gateway' => 'Advcash',
          'country' => 'VEN',
          'currency' => 'USD',
          'payment_mode' => 'Advcash',
          'payment_mode_code' => '',
          'charges_type' => 'combined',
          'fixed_charge' => 0.1,
          'float_charge' => 0.1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.096,
          'pro_float_charge' => 0.096,
          'minimum_deposit' => 1,
          'maximum_deposit' => 50000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '2025-01-21T21:06:20.000000Z',
          'updated_at' => '2025-01-21T21:06:20.000000Z',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0,
        ],
        19 => [
          'id' => 20,
          'method_name' => 'Pix',
          'gateway' => 'BRLA',
          'country' => 'BRA',
          'currency' => 'BRL',
          'payment_mode' => 'bankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.45,
          'float_charge' => 0.2,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.432,
          'pro_float_charge' => 0.192,
          'minimum_deposit' => 50,
          'maximum_deposit' => 150000,
          'minimum_charge' => 0.05,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'BRL,USD',
          'Exchange_rate_float' => 1,
        ],
        20 => [
          'id' => 21,
          'method_name' => 'Bank Transfer',
          'gateway' => 'Khipu',
          'country' => 'CHL',
          'currency' => 'CLP',
          'payment_mode' => 'bankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.45,
          'float_charge' => 0.2,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.432,
          'pro_float_charge' => 0.192,
          'minimum_deposit' => 2000,
          'maximum_deposit' => 7000000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'CLP',
          'Exchange_rate_float' => 0,
        ],
        21 => [
          'id' => 22,
          'method_name' => 'Bank Transfer',
          'gateway' => 'Floid',
          'country' => 'CHL',
          'currency' => 'CLP',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 1,
          'float_charge' => 0.9,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.96,
          'pro_float_charge' => 0.864,
          'minimum_deposit' => 2000,
          'maximum_deposit' => 7000000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'CLP',
          'Exchange_rate_float' => 0,
        ],
        22 => [
          'id' => 23,
          'method_name' => 'Bank Transfer',
          'gateway' => 'Vitawallet',
          'country' => 'CHL',
          'currency' => 'CLP',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.45,
          'float_charge' => 0.2,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.432,
          'pro_float_charge' => 0.192,
          'minimum_deposit' => 2000,
          'maximum_deposit' => 7000000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 1.5,
        ],
        23 => [
          'id' => 24,
          'method_name' => 'Bank Transfer',
          'gateway' => 'Vitawallet',
          'country' => 'ARG',
          'currency' => 'ARS',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.45,
          'float_charge' => 0.2,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.432,
          'pro_float_charge' => 0.192,
          'minimum_deposit' => 20000,
          'maximum_deposit' => 10000000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 1.5,
        ],
        24 => [
          'id' => 25,
          'method_name' => 'Bank Transfer',
          'gateway' => 'Floid',
          'country' => 'PER',
          'currency' => 'PEN',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 1,
          'float_charge' => 0.9,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.96,
          'pro_float_charge' => 0.864,
          'minimum_deposit' => 19,
          'maximum_deposit' => 19000,
          'minimum_charge' => 1,
          'maximum_charge' => 20,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'PEN',
          'Exchange_rate_float' => 0,
        ],
        25 => [
          'id' => 26,
          'method_name' => 'UPI',
          'gateway' => 'Onramp',
          'country' => 'IND',
          'currency' => 'INR',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.5,
          'float_charge' => 0.5,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.48,
          'pro_float_charge' => 0.48,
          'minimum_deposit' => 100,
          'maximum_deposit' => 100000,
          'minimum_charge' => 1,
          'maximum_charge' => 100,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 10,
        ],
        26 => [
          'id' => 27,
          'method_name' => 'IMPS',
          'gateway' => 'Onramp',
          'country' => 'IND',
          'currency' => 'INR',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.5,
          'float_charge' => 0.5,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.48,
          'pro_float_charge' => 0.48,
          'minimum_deposit' => 100,
          'maximum_deposit' => 500000,
          'minimum_charge' => 1,
          'maximum_charge' => 1000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 10,
        ],
        27 => [
          'id' => 28,
          'method_name' => 'Bank Transfer',
          'gateway' => 'TransFi',
          'country' => 'IDN',
          'currency' => 'IDR',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.9,
          'float_charge' => 0.98,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.864,
          'pro_float_charge' => 0.9408,
          'minimum_deposit' => 200000,
          'maximum_deposit' => 160000000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0.3,
        ],
        28 => [
          'id' => 29,
          'method_name' => 'QRIS',
          'gateway' => 'TransFi',
          'country' => 'IDN',
          'currency' => 'IDR',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 1.8,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 1.728,
          'minimum_deposit' => 200000,
          'maximum_deposit' => 4700000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0.3,
        ],
        29 => [
          'id' => 30,
          'method_name' => 'DANA',
          'gateway' => 'TransFi',
          'country' => 'IDN',
          'currency' => 'IDR',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 3.5,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 3.36,
          'minimum_deposit' => 200000,
          'maximum_deposit' => 23000000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0.3,
        ],
        30 => [
          'id' => 31,
          'method_name' => 'OVO',
          'gateway' => 'TransFi',
          'country' => 'IDN',
          'currency' => 'IDR',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 3.5,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 3.36,
          'minimum_deposit' => 200000,
          'maximum_deposit' => 23000000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0.3,
        ],
        31 => [
          'id' => 32,
          'method_name' => 'FPX',
          'gateway' => 'TransFi',
          'country' => 'MYS',
          'currency' => 'MYR',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 2.8,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 2.7,
          'minimum_deposit' => 44,
          'maximum_deposit' => 43000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0.25,
        ],
        32 => [
          'id' => 33,
          'method_name' => 'Bank Transfer',
          'gateway' => 'TransFi',
          'country' => 'MYS',
          'currency' => 'MYR',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 2.8,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 2.7,
          'minimum_deposit' => 44,
          'maximum_deposit' => 43000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0.25,
        ],
        33 => [
          'id' => 34,
          'method_name' => 'Bank Transfer (OR)',
          'gateway' => 'TransFi',
          'country' => 'PHL',
          'currency' => 'PHP',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 1,
          'float_charge' => 1,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.96,
          'pro_float_charge' => 0.96,
          'minimum_deposit' => 580,
          'maximum_deposit' => 580000,
          'minimum_charge' => 1,
          'maximum_charge' => 1000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 5,
        ],
        34 => [
          'id' => 35,
          'method_name' => 'Bank Transfer',
          'gateway' => 'Onramp',
          'country' => 'PHL',
          'currency' => 'PHP',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.4,
          'float_charge' => 0.4,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.384,
          'pro_float_charge' => 0.384,
          'minimum_deposit' => 700,
          'maximum_deposit' => 500000,
          'minimum_charge' => 1,
          'maximum_charge' => 1000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 5,
        ],
        35 => [
          'id' => 36,
          'method_name' => 'GrabPay',
          'gateway' => 'TransFi',
          'country' => 'PHL',
          'currency' => 'PHP',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 2.6,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 2.496,
          'minimum_deposit' => 580,
          'maximum_deposit' => 580000,
          'minimum_charge' => 1,
          'maximum_charge' => 1000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 5,
        ],
        36 => [
          'id' => 37,
          'method_name' => 'PayMaya',
          'gateway' => 'TransFi',
          'country' => 'PHL',
          'currency' => 'PHP',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 2.6,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 2.496,
          'minimum_deposit' => 580,
          'maximum_deposit' => 580000,
          'minimum_charge' => 1,
          'maximum_charge' => 1000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 5,
        ],
        37 => [
          'id' => 38,
          'method_name' => 'QRPH',
          'gateway' => 'TransFi',
          'country' => 'PHL',
          'currency' => 'PHP',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 2.6,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 2.496,
          'minimum_deposit' => 580,
          'maximum_deposit' => 580000,
          'minimum_charge' => 1,
          'maximum_charge' => 1000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 5,
        ],
        38 => [
          'id' => 39,
          'method_name' => 'ShopeePay',
          'gateway' => 'TransFi',
          'country' => 'PHL',
          'currency' => 'PHP',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 2.6,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 2.496,
          'minimum_deposit' => 580,
          'maximum_deposit' => 580000,
          'minimum_charge' => 1,
          'maximum_charge' => 1000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 5,
        ],
        39 => [
          'id' => 40,
          'method_name' => 'GCash',
          'gateway' => 'TransFi',
          'country' => 'PHL',
          'currency' => 'PHP',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 3.5,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 3.36,
          'minimum_deposit' => 580,
          'maximum_deposit' => 580000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 5,
        ],
        40 => [
          'id' => 41,
          'method_name' => 'FAST',
          'gateway' => 'Onramp',
          'country' => 'TUR',
          'currency' => 'TRY',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.5,
          'float_charge' => 0.5,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.48,
          'pro_float_charge' => 0.48,
          'minimum_deposit' => 300,
          'maximum_deposit' => 200000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 1.2,
        ],
        41 => [
          'id' => 42,
          'method_name' => 'Bank Transfer',
          'gateway' => 'Onramp',
          'country' => 'ARE',
          'currency' => 'AED',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.5,
          'float_charge' => 0.5,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.48,
          'pro_float_charge' => 0.48,
          'minimum_deposit' => 50,
          'maximum_deposit' => 371000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 2,
        ],
        42 => [
          'id' => 43,
          'method_name' => 'Bank Transer',
          'gateway' => 'Onramp',
          'country' => 'LKA',
          'currency' => 'LKR',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.5,
          'float_charge' => 0.5,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.48,
          'pro_float_charge' => 0.48,
          'minimum_deposit' => 1000,
          'maximum_deposit' => 20000,
          'minimum_charge' => 1,
          'maximum_charge' => 1000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 2,
        ],
        43 => [
          'id' => 44,
          'method_name' => 'Bank Transfer',
          'gateway' => 'TransFi',
          'country' => 'THA',
          'currency' => 'THB',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 1.5,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 1.44,
          'minimum_deposit' => 300,
          'maximum_deposit' => 330000,
          'minimum_charge' => 1,
          'maximum_charge' => 1000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => 0.2,
        ],
        44 => [
          'id' => 45,
          'method_name' => 'Bank Transfer',
          'gateway' => 'TransFi',
          'country' => 'VNM',
          'currency' => 'VND',
          'payment_mode' => 'BankTransfer',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 1.2,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 1.152,
          'minimum_deposit' => 250000,
          'maximum_deposit' => 250000000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => NULL,
        ],
        45 => [
          'id' => 46,
          'method_name' => 'MOMO',
          'gateway' => 'TransFi',
          'country' => 'VNM',
          'currency' => 'VND',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 1.6,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 1.536,
          'minimum_deposit' => 250000,
          'maximum_deposit' => 250000000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => NULL,
        ],
        46 => [
          'id' => 47,
          'method_name' => 'VietellePay',
          'gateway' => 'TransFi',
          'country' => 'VNM',
          'currency' => 'VND',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 1.6,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 1.536,
          'minimum_deposit' => 250000,
          'maximum_deposit' => 250000000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => NULL,
        ],
        47 => [
          'id' => 48,
          'method_name' => 'Zalo',
          'gateway' => 'TransFi',
          'country' => 'VNM',
          'currency' => 'VND',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 2.5,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 2.4,
          'minimum_deposit' => 250000,
          'maximum_deposit' => 250000000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => 'USD',
          'Exchange_rate_float' => NULL,
        ],
        48 => [
          'id' => 49,
          'method_name' => 'VietQR',
          'gateway' => 'TransFi',
          'country' => 'VNM',
          'currency' => 'VND',
          'payment_mode' => 'Wallet',
          'payment_mode_code' => '',
          'charges_type' => 'Combined',
          'fixed_charge' => 0.2,
          'float_charge' => 1.8,
          'settlement_time' => 0.1,
          'pro_fixed_charge' => 0.192,
          'pro_float_charge' => 1.728,
          'minimum_deposit' => 250000,
          'maximum_deposit' => 250000000,
          'minimum_charge' => 1,
          'maximum_charge' => 10000,
          'cutoff_hrs_start' => '',
          'cutoff_hrs_end' => '',
          'Working_hours_start' => '',
          'Working_hours_end' => '',
          'created_at' => '',
          'updated_at' => '',
          'deleted_at' => '',
          'required_extra_data' => '',
          'Base_Currency' => '',
          'Exchange_rate_float' => NULL,
        ],
    ];
    

    foreach ($payins as $payin) {
        PayinMethods::where([
            'method_name'         => $payin['method_name'],
            'gateway'             => $payin['gateway'],
            'country'             => $payin['country'],
            'currency'            => $payin['currency'],
            'payment_mode'        => $payin['payment_mode'],
            'charges_type'        => $payin['charges_type'],
            'fixed_charge'        => $payin['fixed_charge'],
            'float_charge'        => $payin['float_charge'],
            'estimated_delivery'  => $payin['estimated_delivery'],
            'pro_fixed_charge'    => $payin['pro_fixed_charge'],
            'pro_float_charge'    => $payin['pro_float_charge'],
        ])->update([
            "base_currency" => $payout['base_currency'], 
            "exchange_rate_float" => $payout["exchange_rate_float"]
        ]);
    }
});





Route::view('onramp', 'welcome');



Route::get('deposits', function (){
    $wallet = Wallet::where('slug', 'default')->delete();
    return Deposit::latest()->limit(10)->get();
});


Route::get('/', function () {
    return redirect()->to('https://yativo.com');
});


Route::any('/coinbase/onramp/token', [CoinbaseOnrampController::class, 'getSessionToken']);
Route::any('/coinbase/onramp/url', [CoinbaseOnrampController::class, 'generateOnrampUrl']);

Route::domain(env('CHECKOUT_DOMAIN'))->group(function () {
    Route::get('process-payin/{id}/paynow', [CheckoutController::class, 'show'])->name('checkout.url');
});


Route::get('/wallets/{uuid}', [VitaWalletTestController::class, 'getWalletByUUID']);
Route::get('/wallets', [VitaWalletTestController::class, 'listWallets']);
Route::post('/transactions', [VitaWalletTestController::class, 'createTransaction']);
Route::post('/withdrawals', [VitaWalletTestController::class, 'createWithdrawal']);
Route::post('/vita-send', [VitaWalletTestController::class, 'createVitaSend']);
Route::get('/transactions', [VitaWalletTestController::class, 'listTransactions']);
Route::get('/wallet-transactions/{uuid}', [VitaWalletTestController::class, 'listWalletTransactions']);

Route::any('callback/webhook/transfi', [TransFiController::class, 'processWebhook'])->name('transfi.callback.success');

Route::group([], function () {
    Route::get('checkout/advcash/{checkout_hash}', [AdvcashController::class, 'checkout'])->name('advcash.checkout.url');
});

// Route::any('bitso/withdrawal', [BitsoController::class, 'initiateWithdrawal'])->name('bitso.withdrawal');

Route::group([], function () {
    Route::get('callback/payIn/onramp', [OnrampService::class, 'payInCallback'])->name('onramp.payIn.callback');
    Route::get('callback/payOutn/onramp', [OnrampService::class, 'payOutCallback'])->name('onramp.payOut.callback');

    Route::any('callback/webhook/coinpayments', [CryptoWalletsController::class, 'wallet_webhook']);
    Route::any('callback/webhook/local-payments', [LocalPaymentWebhookController::class, 'handle']);
    Route::any('callback/webhook/bitso', [ControllersBitsoController::class, 'deposit_webhook'])->name('bitso.cop.deposit');

    // Bridge webhook callback
    Route::any('callback/webhook/bridge', [BridgeController::class, 'BridgeWebhook'])->name('bridge.callback.success');
    Route::any('callback/webhook/customer-kyc', [DojahVerificationController::class, 'KycWebhook'])->name('kyc.callback.success');


    Route::any('callback/webhook/vitawallet', [VitaWalletController::class, 'callback'])->name('vitawallet.callback.success');
    Route::any('callback/webhook/deposit/vitawallet/{quoteId}', [VitaWalletController::class, 'deposit_callback'])->name('vitawallet.deposit.callback.success');

    Route::any('callback/webhook/floid', [FlowController::class, 'callback'])->name('floid.callback.success');
    Route::any('callback/webhook/floid-redirect', [FlowController::class, 'callback'])->name('floid.callback.redirect');

    Route::post("callback/webhook/virtual-account-webhook", [VirtualAccountsController::class, 'virtualAccountWebhook'])->name('business.virtual-account.virtualAccountWebhook');
    Route::any('callback/wallet/webhook/{userId}/{currency}', [CryptoWalletsController::class, 'walletWebhook'])->name('crypto.wallet.address.callback');
})->withoutMiddleware(VerifyCsrfToken::class);

Route::any('cron', [CronController::class, 'index'])->name('cron.index');


Route::post('process-paxos', [PaxosController::class, 'processPexos'])->name('process.pexos');


Route::match(['get', 'post'], 'login', function () {
    $json = [
        "endpoint" => request()->fullUrl(),
        "ip" => request()->ip(),
        "userAgent" => request()->userAgent(),
        "payload" => request()->all(),
    ];
    return get_error_response([
        "error" => "Sorry we could not find a matching route for this request",
        "info" => $json
    ]);
});


Route::fallback(function () {
    $json = [
        "endpoint" => request()->fullUrl(),
        "ip" => request()->ip(),
        "userAgent" => request()->userAgent(),
        "payload" => request()->all(),
    ];
    Log::channel('missing_route')->error(json_encode($json));
    return get_error_response([
        "error" => "Sorry we could not find a matching route for this request",
        "info" => $json
    ]);
});
