name: Cleanup Artifacts

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - uses: geekyeggo/delete-artifact@v5
      with:
          name: |
              *.zip 