name: Deploy to GCP

on:
  push:
    branches: [gcp_cloud]
  pull_request:
    branches: [gcp_cloud]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Install Composer Dependencies
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist


      - name: Deploy to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/yativo
            # Fetch and reset to remote main branch
            git fetch origin
            git reset --hard origin/gcp_cloud

            chown -R www-data:www-data /var/www/yativo
            chmod -R 775 /var/www/yativo/storage /var/www/yativo/bootstrap/cache            
            
            # Optionally clear Laravel's cache
            php artisan config:clear
            php artisan cache:clear
            php artisan storage:link

            # Ensure proper permissions for logs directory and its files (append mode)
            sudo chown -R www-data:www-data storage
            sudo chmod -R 775 storage
            sudo chmod -R g+s storage/logs
            
            touch storage/logs/laravel.log
            echo "Log file is ready and writable" >> storage/logs/laravel.log
